### ISSUE TITLE
gallerize_cli runtime error

### ISSUE THREAD

**Issue by restot** [blakehilscher/gallerize#4]
on my mac OS X 10.10 after run gallerize_cli i have the error:
/Users/useruser/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- exifr (LoadError)
	from /Users/useruser/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/useruser/.rvm/gems/ruby-2.3.0/gems/gallerize-cli-0.5.0/lib/gallerize_cli/image/version.rb:2:in `<top (required)>'
	from /Users/useruser/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/useruser/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/useruser/.rvm/gems/ruby-2.3.0/gems/gallerize-cli-0.5.0/lib/gallerize_cli/image.rb:1:in `<top (required)>'
	from /Users/useruser/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/useruser/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/useruser/.rvm/gems/ruby-2.3.0/gems/gallerize-cli-0.5.0/lib/gallerize_cli/directory.rb:2:in `<top (required)>'
	from /Users/useruser/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/useruser/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/useruser/.rvm/gems/ruby-2.3.0/gems/gallerize-cli-0.5.0/lib/gallerize_cli.rb:1:in `<top (required)>'
	from /Users/useruser/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/useruser/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/useruser/.rvm/gems/ruby-2.3.0/gems/gallerize-cli-0.5.0/bin/gallerize_cli:9:in `<top (required)>'
	from /Users/useruser/.rvm/gems/ruby-2.3.0/bin/gallerize_cli:22:in `load'
	from /Users/useruser/.rvm/gems/ruby-2.3.0/bin/gallerize_cli:22:in `<main>'
	from /Users/useruser/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/useruser/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by restot** [comment]
i try to use ruby 2.3.0 and 2.3.3, have same error

**Comment by jameshibbard** [comment]
Just install the missing gem:

```
gem install exifr
```
